FROM golang:1.26 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o image-service ./cmd/app


FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/image-service .

EXPOSE 8080

ENTRYPOINT ["./image-service"]